#!/bin/bash

# Dark Facebook Cloner (DFC) v2.5 README

echo -e "\033[1;31m"
echo "=============================================================="
echo "        Dark Facebook Cloner (DFC) v2.5"
echo "=============================================================="
echo -e "\033[0m"

echo -e "\033[1;33m"
echo "A tool to automate Facebook account creation for ethical testing"
echo -e "\033[0m"

echo ""
echo "--------------------------------------------------------------"
echo "📋 Table of Contents"
echo "--------------------------------------------------------------"
echo "1. What is DFC?"
echo "2. What Does DFC Do?"
echo "3. Installation"
echo "4. Usage"
echo "5. Contact"
echo "6. Disclaimer"
echo ""

echo "--------------------------------------------------------------"
echo "🌟 What is DFC?"
echo "--------------------------------------------------------------"
echo "Dark Facebook Cloner (DFC) is a Python-based tool by The Realm of Classic Hackers (T.R.C.H) for automating the creation of Facebook accounts using temporary emails and proxies. It’s designed for ethical research, such as testing APIs or analyzing platforms in controlled environments."
echo ""
echo -e "\033[1;31m⚠️ Important: Use DFC responsibly. Unauthorized account creation violates Facebook’s Terms of Service and may have legal consequences.\033[0m"
echo ""

echo "--------------------------------------------------------------"
echo "✨ What Does DFC Do?"
echo "--------------------------------------------------------------"
echo "- Generates temporary email addresses via the Mail.tm API."
echo "- Uses proxies included in the repository (proxies.txt) for anonymity."
echo "- Creates random user profiles (names, birthdays, genders) with the Faker library."
echo "- Registers Facebook accounts via the Facebook API."
echo "- Saves account details (email, ID, password, token) to username.txt."
echo ""

echo "--------------------------------------------------------------"
echo "🛠️ Installation"
echo "--------------------------------------------------------------"
echo "Get DFC running on your system with these steps:"
echo ""
echo "Prerequisites:"
echo "- Python 3.6+: Download from https://www.python.org/downloads/"
echo "- pip: Included with Python for package management"
echo "- Git: Optional, from https://git-scm.com/downloads"
echo ""
echo "Steps:"
echo "1. Clone or download the repository (includes proxies.txt):"
echo "   git clone https://github.com/TheRealofClassicHackers/Dark_Facebook_Clone.git"
echo "   cd Dark_Facebook_Clone"
echo ""
echo "2. Install Python dependencies:"
echo "   pip install requests faker colorama"
echo ""
echo "3. Verify API credentials:"
echo "   - DFC uses hardcoded Facebook API credentials in Dark_Facebook_Clone.py."
echo "   - If they fail, update api_key and secret in the register_facebook_account function or contact us."
echo ""
echo "4. Run the tool:"
echo "   python dfc.py"
echo ""
echo "Notes:"
echo "- The repository includes a proxies.txt file with pre-installed proxies."
echo "- Ensure a stable internet connection."
echo "- Account details are saved to username.txt."
echo ""

echo "--------------------------------------------------------------"
echo "🚀 Usage"
echo "--------------------------------------------------------------"
echo "1. Run the script:"
echo "   python dfc.py"
echo ""
echo "2. Follow prompts:"
echo "   - Enter the number of accounts to create."
echo "   - Monitor the console for progress and errors."
echo "   - Check username.txt for account details (email, ID, password, token)."
echo ""
echo "3. Tips:"
echo "   - The included proxies.txt should work, but you can update it with new proxies if needed."
echo "   - Watch for API rate limit warnings."
echo ""

echo "--------------------------------------------------------------"
echo "📞 Contact"
echo "--------------------------------------------------------------"
echo "Questions or issues? Reach out:"
echo ""
echo "<a href=\"https://www.facebook.com/profile.php?id=61555424416864\">"
echo "  <button style=\"background-color: #1877F2; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; font-size: 14px;\">"
echo "    Contact T.R.C.H on Facebook"
echo "  </button>"
echo "</a>"
echo ""

echo "--------------------------------------------------------------"
echo "⚖️ Disclaimer"
echo "--------------------------------------------------------------"
echo "DFC is for educational and research purposes only. The developers (@TheRealofClassicHackers) are not liable for misuse or damages. Users must:"
echo "- Use DFC ethically and legally, with proper authorization."
echo "- Comply with Facebook’s Terms of Service and laws."
echo "- Accept responsibility for consequences like bans or legal action."
echo ""
echo -e "\033[1;33mBuilt with 💻 by TheRealofClassicHackers\033[0m"
echo -e "\033[1;33mFollow us on https://www.facebook.com/profile.php?id=61555424416864 for updates!\033[0m"
echo "--------------------------------------------------------------"
